package blb.vistas;

import blb.controlador.AdminControlador;
import blb.modelo.Administracion;
import blb.utilidad.Utilidades;
import javax.swing.JOptionPane;

public class ActualizarAdministracion extends javax.swing.JPanel {

    
    public ActualizarAdministracion() {
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        e_DiaTxt = new javax.swing.JTextField();
        e_MoraTxt = new javax.swing.JTextField();
        actualizarEstudianteBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p_DiaTxt = new javax.swing.JTextField();
        p_MoraTxt = new javax.swing.JTextField();
        actualizarProfesorBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        e_CantidadTxt = new javax.swing.JTextField();
        p_CantidadTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de actualizacion de prestamos de libros");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Días de préstamo a estudiantes:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Recargo de mora a estudiantes:");

        actualizarEstudianteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        actualizarEstudianteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-de-carga.png"))); // NOI18N
        actualizarEstudianteBtn.setText("Actualizar");
        actualizarEstudianteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarEstudianteBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Días de préstamo a profesores:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Recargo de mora a profesores:");

        actualizarProfesorBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        actualizarProfesorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-de-carga.png"))); // NOI18N
        actualizarProfesorBtn.setText("Actualizar");
        actualizarProfesorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarProfesorBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Registro de Actividad");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Cantidad de materiales a prestar:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cantidad de materiales a prestar:");

        p_CantidadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_CantidadTxtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estudiar.png"))); // NOI18N
        jLabel10.setText("ESTUDIANTES");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profesor.png"))); // NOI18N
        jLabel11.setText("PROFESORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(8, 8, 8)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(e_CantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(e_DiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e_MoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(p_CantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(p_MoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(p_DiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel10)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)))
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(actualizarEstudianteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actualizarProfesorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel11))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(e_CantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(p_CantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(e_DiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_DiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(e_MoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualizarEstudianteBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(p_MoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualizarProfesorBtn)))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarProfesorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProfesorBtnActionPerformed

        String p_dia = p_DiaTxt.getText();
        String p_mora = p_MoraTxt.getText();
        String p_cantidad = p_CantidadTxt.getText();

        if (p_DiaTxt.getText().equals("") || p_MoraTxt.getText().equals("") || p_CantidadTxt.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Error, no puedes dejar campos vacíos...");
            return;
        }
        
        if (!Utilidades.verificarNumero(p_dia) || !Utilidades.verificarNumero(p_mora) || !Utilidades.verificarNumero(p_cantidad)) {
            
            JOptionPane.showMessageDialog(null, "Error, has ingresado un dato que no es númerico.....");
            return;
        }

        if (Integer.parseInt(p_dia) <= 0 || Integer.parseInt(p_mora) <= 0 || Integer.parseInt(p_cantidad) <= 0) {

            JOptionPane.showMessageDialog(null, "Error, los campos de día y mora deben de ser mayores que 0...");
            return;
        }

        try {

            AdminControlador ad = new AdminControlador();
            Administracion admin = new Administracion();

            admin.setDiaProfesor(Integer.parseInt(p_dia));
            admin.setMoraProfesor(Integer.parseInt(p_mora));
            admin.setMaterialProfesor(Integer.parseInt(p_cantidad));
            ad.actualizarAdministracionProfesor(admin);

            JOptionPane.showMessageDialog(null, "Los campos del profesor han sido modificado con exito...");

            p_DiaTxt.setText("");
            p_MoraTxt.setText("");
            p_CantidadTxt.setText("");

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_actualizarProfesorBtnActionPerformed

    private void actualizarEstudianteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarEstudianteBtnActionPerformed

        String e_dia = e_DiaTxt.getText();
        String e_mora = e_MoraTxt.getText();
        String e_cantidad = e_CantidadTxt.getText();

        if (e_DiaTxt.getText().equals("") || e_MoraTxt.getText().equals("") || e_CantidadTxt.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Error, no puedes dejar campos vacíos...");
            return;
        }
        
        if (!Utilidades.verificarNumero(e_dia) || !Utilidades.verificarNumero(e_mora) || !Utilidades.verificarNumero(e_cantidad)) {
            
            JOptionPane.showMessageDialog(null, "Error, has ingresado un dato que no es númerico.....");
            return;
        }
        
        if (Integer.parseInt(e_dia) <= 0 || Integer.parseInt(e_mora) <= 0 || Integer.parseInt(e_cantidad) <= 0) {

            JOptionPane.showMessageDialog(null, "Error, los campos de día y mora deben de ser mayores que 0...");
            return;
        }

        try {

            AdminControlador ad = new AdminControlador();
            Administracion admin = new Administracion();

            admin.setDiaEstudiante(Integer.parseInt(e_dia));
            admin.setMoraEstudiante(Integer.parseInt(e_mora));
            admin.setMaterialEstudiante(Integer.parseInt(e_cantidad));
            ad.actualizarAdministracionEstudiante(admin);

            JOptionPane.showMessageDialog(null, "Los campos del estudiante han sido modificado con exito...");

            e_DiaTxt.setText("");
            e_MoraTxt.setText("");
            e_CantidadTxt.setText("");

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_actualizarEstudianteBtnActionPerformed

    private void p_CantidadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_CantidadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_CantidadTxtActionPerformed

    public void cargarDatos() {

        AdminControlador ac = new AdminControlador();
        Administracion admin = ac.consultarAdmin();

        e_DiaTxt.setText(String.valueOf(admin.getDiaEstudiante()));
        e_MoraTxt.setText(String.valueOf(admin.getMoraEstudiante()));
        e_CantidadTxt.setText(String.valueOf(admin.getMaterialEstudiante()));

        p_DiaTxt.setText(String.valueOf(admin.getDiaProfesor()));
        p_MoraTxt.setText(String.valueOf(admin.getMoraProfesor()));
        p_CantidadTxt.setText(String.valueOf(admin.getMaterialProfesor()));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarEstudianteBtn;
    private javax.swing.JButton actualizarProfesorBtn;
    private javax.swing.JTextField e_CantidadTxt;
    private javax.swing.JTextField e_DiaTxt;
    private javax.swing.JTextField e_MoraTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField p_CantidadTxt;
    private javax.swing.JTextField p_DiaTxt;
    private javax.swing.JTextField p_MoraTxt;
    // End of variables declaration//GEN-END:variables
}
