package blb.vistas;


import blb.controlador.AdminControlador;
import blb.controlador.MaterialControlador;
import blb.controlador.PrestamoControlador;
import blb.controlador.UsuarioControlador;
import blb.modelo.Administracion;
import blb.modelo.Materiales;
import blb.modelo.Prestamos;
import blb.modelo.Usuarios;
import blb.utilidad.Utilidades;
import javax.swing.JOptionPane;



public class DevolverMaterialAdmin extends javax.swing.JPanel {

    //SE CONSULTA LA BASE DE DATOS PARA OBTENER EL COSTO POR ENTREGA TARDIA DE ACUERDO A SU PROFESION.....
    AdminControlador ac = new AdminControlador();
    Administracion admin = ac.consultarAdmin();
    
    private final int diaLimiteEstudiante = admin.getDiaEstudiante();
    private final int recargoMoraEstudiante = admin.getMoraEstudiante();
    
    private final int diaLimiteProfesor = admin.getDiaProfesor();
    private final int recargoMoraProfesor = admin.getMoraProfesor();
    
    public DevolverMaterialAdmin() {
        initComponents();
        cargarDatos();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        materialTxt = new javax.swing.JTextField();
        devolverBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de devolución");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese ID de material:");

        materialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialTxtActionPerformed(evt);
            }
        });

        devolverBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        devolverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caja-de-devolucion.png"))); // NOI18N
        devolverBtn.setText("Devolver");
        devolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese el ID de usuario:");

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tblPrestamos);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/devolucion-de-producto.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(devolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(materialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(devolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(materialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void devolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverBtnActionPerformed

        String id_u = userTxt.getText();
        String id_l = materialTxt.getText();

        if (materialTxt.getText().equals("") || userTxt.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Error, no puedes dejar campos vacíos...");
            return;
        }
        
        if (!id_u.matches("^[A-Za-z]{2}\\d{6}$")) {
            JOptionPane.showMessageDialog(null, "El No de ID debe de conterner 2 letras y 6 digitos...");
            return;
        }
        
        if (!id_l.matches("^[A-Za-z]{3}\\d{4}$")) {
            JOptionPane.showMessageDialog(null, "El codigo del material debe de conterner 3 letras y 4 digitos...");
            return;
        }

        try {
            
            UsuarioControlador uc = new UsuarioControlador();
            Usuarios u = uc.consultarPorId(id_u);
            
            //VALIDACION DE USUARIO REGISTRADO.....
            if (u == null) {
                JOptionPane.showMessageDialog(null, "Error, no se encontró ningun usuario con ID: " + id_u + " favor ingresar un ID válido...");
                return;
            } 

            MaterialControlador lc = new MaterialControlador();
            Materiales l = lc.consultarMaterial(id_l);
            
            //VALIDACION DE MATERIAL REGISTRADO.....
            if (l == null) {
                JOptionPane.showMessageDialog(null, "Error, no se encontró ningun material con ID: " + id_l + " favor ingresar un ID válido...");
                return;
            } 

            PrestamoControlador pc = new PrestamoControlador();
            Prestamos p = pc.getLending(u, l);
            
            //VALIDACION DE PRESTAMOS ACTUALES.....
            if (p == null) {
                JOptionPane.showMessageDialog(null, "Error, no se pudo encontrar prestamo correspondiente al material que estas tratando de devolver...");
                return;
            }

            p.setF_devolucion(Utilidades.fechaActual());
            pc.modificar(p);

            l.setUnidades(l.getUnidades() + 1);
            lc.modificar(l);
            JOptionPane.showMessageDialog(null, "Material ID: " + l.getCodId() + " devuelto exitosamente...");
            
            int dias = Utilidades.diferenciasDeFechas(p.getF_prestamos(), Utilidades.fechaActual());
            
            //SE APLICA RECARGO A ESTUDIANTES DE ACUERDO A LA INFORMACION EN BASE DE DATOS.....
            if (u.getOficio().equals("ESTUDIANTE") && dias > diaLimiteEstudiante) {

                int dia_retraso = dias - diaLimiteEstudiante;
                int recargo = dia_retraso * recargoMoraEstudiante;

                u.setRecargo_mora(u.getRecargo_mora() + recargo);
                uc.sancionar(u);

                JOptionPane.showMessageDialog(null, "RECARGO POR DEVOLUCIÓN TARDÍA HA SIDO APLICADO, EL TOTAL A PAGAR ES DE: " + recargo + "$");

            } 
            //SE APLICA RECARGO A PROFESORES DE ACUERDO A LA INFORMACION EN BASE DE DATOS.....
            else if (u.getOficio().equals("PROFESOR") && dias > diaLimiteEstudiante) {
                
                int dia_retraso = dias - diaLimiteProfesor;
                int recargo = dia_retraso * recargoMoraProfesor;

                u.setRecargo_mora(u.getRecargo_mora() + recargo);
                uc.sancionar(u);

                JOptionPane.showMessageDialog(null, "RECARGO POR DEVOLUCIÓN TARDÍA HA SIDO APLICADO, EL TOTAL A PAGAR ES DE: " + recargo + "$");

            }
            
            userTxt.setText("");
            materialTxt.setText("");

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_devolverBtnActionPerformed

    private void materialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialTxtActionPerformed

    public void cargarDatos() {
        PrestamoControlador mc = new PrestamoControlador();
        tblPrestamos.setModel(mc.listarPrestamos());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devolverBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materialTxt;
    private javax.swing.JTable tblPrestamos;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
