package blb.vistas;


import blb.controlador.AdminControlador;
import blb.controlador.MaterialControlador;
import blb.controlador.PrestamoControlador;
import blb.controlador.UsuarioControlador;
import blb.modelo.Administracion;
import blb.modelo.Materiales;
import blb.modelo.Prestamos;
import blb.modelo.Usuarios;
import blb.utilidad.Utilidades;
import javax.swing.JOptionPane;


public class PrestarMaterial extends javax.swing.JPanel {

    /**
     * Creates new form Vista1
     */
    public PrestarMaterial() {
        initComponents();
        cargarDatos();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        material_idTxt = new javax.swing.JTextField();
        prestarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMateriales = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de prestamos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese el ID de material:");

        prestarBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prestarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedir-prestado.png"))); // NOI18N
        prestarBtn.setText("Prestar");
        prestarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestarBtnActionPerformed(evt);
            }
        });

        tblMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tblMateriales);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/devolucion-de-producto.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(prestarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(material_idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(material_idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prestarBtn))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prestarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestarBtnActionPerformed
        
        String id_U = LogIn.userTxt.getText().toUpperCase();
        String id_P = LogIn.passwordTxt.getText().toUpperCase();
        
        String id_l = material_idTxt.getText().toUpperCase();

        if (material_idTxt.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Error, no puedes dejar campos vacíos...");
            return;
        }
        
        if (!id_l.matches("^[A-Za-z]{3}\\d{4}$")) {
            JOptionPane.showMessageDialog(null, "El codigo del material debe de conterner 3 letras y 4 digitos...");
            return;
        }

        try {
            
            AdminControlador ac = new AdminControlador();
            Administracion admin = ac.consultarAdmin();
            
            UsuarioControlador uc = new UsuarioControlador();
            Usuarios u = uc.log_In(id_U, id_P);

            MaterialControlador lc = new MaterialControlador();
            Materiales l = lc.consultarMaterial(id_l);
            
            //VALIDACION DE MATERIAL REGISTRADO.....
            if (l == null) {
                JOptionPane.showMessageDialog(null, "Error, no se encontró ningun material con ID: " + id_l + " favor ingresar un ID válido...");
                return;
            } 
            //VALIDACION DE DISPONIBILIDAD DE MATERIAL A PRESTAR.....
            else if (l.getUnidades() < 1) {
                JOptionPane.showMessageDialog(null, "Error, el material que estas buscando no esta disponible...");
                return;
            }

            PrestamoControlador pc = new PrestamoControlador();
            Prestamos pActual = pc.getLending(u, l);
            
            //VALIDACION DE PRESTAMOS ACTUALES.....
            if (pActual != null) {
                JOptionPane.showMessageDialog(null, "Error, no puedes prestar el mismo material, vuelve a intentarlo...");
                return;
            }

            Prestamos p;
            
            //VALIDACION PARA ESTUDIANTES SOLO TIENE PERMITIDO N PRESTAMOS DE ACUERDO A LA INFORMACION EN BASE DE DATOS.....
            if (u.getOficio().equals("ESTUDIANTE") && pc.cantidadPrestamos(u) >= admin.getMaterialEstudiante()) {
                JOptionPane.showMessageDialog(null, "Lo siento, solo tienes permitidio prestar " + admin.getMaterialEstudiante() + " materiales como máximo...");
                return;
            }

            //VALIDACION PARA PROFESORES SOLO TIENE PERMITIDO N PRESTAMOS DE ACUERDO A LA INFORMACION EN BASE DE DATOS.....
            if (u.getOficio().equals("PROFESOR") && pc.cantidadPrestamos(u) >= admin.getMaterialProfesor()) {
                JOptionPane.showMessageDialog(null, "Lo siento, solo tienes permitidio prestar  " + admin.getMaterialProfesor() + "  materiales como máximo...");
                return;
            }

            if (u.getOficio().equals("ADMINISTRADOR"));
    
            //VALIDACION PARA USUARIOS CON RECARGO POR ENTREGA TARDIA.....
            if (u.getRecargo_mora() != 0) {
                JOptionPane.showMessageDialog(null, "Lo siento, Se ha detectado que tienes un recargo por entrega tardía de: " + u.getRecargo_mora()
                        + "$,  Favor cancelar el recargo para que puedas prestar otro materiales...");
                return;
            }
            
            String idUser = u.getIdUser();
            String nombreUser = u.getNombre()+ " " + u.getApellido();
            String idMaterial = l.getCodId();
            String nombreMaterial = l.getNombreMaterial();

            p = new Prestamos(idUser,nombreUser,idMaterial,nombreMaterial,Utilidades.fechaActual());
                    
            pc.registrar(p);

            l.setUnidades(l.getUnidades() - 1);
            lc.modificar(l);
            JOptionPane.showMessageDialog(null, "Material ID: " + l.getCodId() + " prestado exitosamente...");

            material_idTxt.setText("");

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_prestarBtnActionPerformed

    public void cargarDatos() {
        MaterialControlador mc = new MaterialControlador();
        tblMateriales.setModel(mc.listarMateriales());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField material_idTxt;
    private javax.swing.JButton prestarBtn;
    public static javax.swing.JTable tblMateriales;
    // End of variables declaration//GEN-END:variables
}
